### ISSUE TITLE
ino should be smarter about current dir it is run in

### ISSUE THREAD

**Issue by pfalcon** [amperka/ino#43] opened 2012-09-10 15:30 UTC
```
ino init -t blink
cd src
vi sketch.ino
ino build
```

Whoa:

```
Searching for Board description file (boards.txt) ... /usr/share/arduino/hardware/arduino/boards.txt
Searching for Arduino lib version file (version.txt) ... /usr/share/arduino/lib/version.txt
Detecting Arduino software version ...  1.0 (1.0)
Searching for Arduino core library ... /usr/share/arduino/hardware/arduino/cores/arduino
Searching for Arduino standard libraries ... /usr/share/arduino/libraries
Searching for Arduino variants directory ... /usr/share/arduino/hardware/arduino/variants
Searching for avr-gcc ... /usr/bin/avr-gcc
Searching for avr-g++ ... /usr/bin/avr-g++
Searching for avr-ar ... /usr/bin/avr-ar
Searching for avr-objcopy ... /usr/bin/avr-objcopy
Traceback (most recent call last):
  File "/usr/local/bin/ino", line 6, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/ino/runner.py", line 63, in main
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/ino/commands/build.py", line 210, in run
    self.scan_dependencies()
  File "/usr/local/lib/python2.7/dist-packages/ino/commands/build.py", line 172, in scan_dependencies
    lib_dirs = [self.e.arduino_core_dir] + list_subdirs(self.e.lib_dir) + list_subdirs(self.e.arduino_libraries_dir)
  File "/usr/local/lib/python2.7/dist-packages/ino/utils.py", line 41, in list_subdirs
    entries = [e for e in os.listdir(dirname) if e not in exclude and not e.startswith('.')]
OSError: [Errno 2] No such file or directory: 'lib'
```

Tested with ino HEAD 1bf4a15d241e8908798606624430b64972564f26

**Comment by ratkins** [comment] 2012-10-15 04:56
+1, I just came here to write the exact same bug report.

**Comment by geetarista** [comment] 2012-12-10 06:53
+1 This also means that you can't even use this tool with the Arduino examples or other projects that don't use this directory structure.

**Comment by Kernald** [comment] 2013-01-03 20:49
As a sidenote, you'll get the exception about lib not found even if you have a src directory with actual sources inside of it, but no lib folder (tested against the 0.3.4 packaged in Archlinux AUR)

**Comment by sibblegp** [comment] 2013-01-04 00:23
+1

**Comment by mchughj** [comment] 2013-02-17 04:34
Isn't the issue here that 'ino build' doesn't work when you have changed into the source directory?  As part of 'ino init' a library directory was created, right?  So the problem is that 'ino build' is not resilient to being executed from within a subdirectory for the project directory.  Shouldn't the correct fix be to address that issue?

**Comment by mrAZex** [comment] 2013-03-24 14:52
+1

**Comment by 12qu** [comment] 2013-07-01 09:34
+1, came here specifically to request this myself.

**Comment by skwash** [comment] 2013-08-04 16:53
+1

**Comment by nkrkv** [comment] 2013-09-24 08:18
Fixed in 0.3.6

**Closed as completed by nkrkv** 2013-09-24 08:18 UTC

**Comment by jenschr** [comment] 2014-01-06 22:00
Nope. Fails on Ubuntu with 0.3.6 (running under Parallels on OSX)

**Comment by chrisspen** [comment] 2014-10-26 03:37
Why was this marked as closed? It's not fixed...

**Comment by Dropter** [comment] 2015-12-22 07:32
Still not fixed...

**Comment by chrisspen** [comment] 2015-12-22 09:04
Unfortunately, this is a dead project. I recommend trying [ano](https://github.com/scottdarch/Arturo) which is a fork of ino that supports slightly newer versions of Arduino, but it too is falling behind.

**Comment by Dropter** [comment] 2015-12-22 20:44
Thanks chrisspen, I should've checked before hehe
