### ISSUE TITLE
Arcuino-mpide Comparison

### ISSUE THREAD

**Issue by rei-vilo** [amperka/ino#14] opened 2011-12-30 21:36 UTC
For an extension of Ino for chipKIT mpide, please find:
- Arduino-mpide Comparison — [Directories and Files](https://docs.google.com/open?id=0B9EofSODZdANYTYyYTM1ZTAtYmI5YS00NjY4LWEwY2YtZGRhNTEwMTU4YTk2)
- Arduino-mpide Comparison — [Build and Upload Traces](https://docs.google.com/open?id=0B9EofSODZdANYTc5NDlhMmMtZDNiZC00YzRhLWJiZjQtZmVhMjUxZDBkZWY0)

for the following cases
- Arduino IDE 0023 for UNO
- mpide 0023 for Arduino UNO
- mpide 0023 for chpKIT UNO32

The really nice thing about mpide is that it handles both platforms — hence its name **M**ulti-**P**latform **IDE**.

Should you need more details, feel free to ask.

**Comment by nkrkv** [comment] 2013-09-24 08:15
Duplicate of #5

**Closed as completed by nkrkv** 2013-09-24 08:15 UTC
